# Generated by Django 4.2.8 on 2023-12-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.coursecategory'),
        ),
    ]
