# Generated by Django 4.2.8 on 2023-12-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_exam_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-course_category'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='upcomingexam',
            options={'ordering': ['-exam'], 'verbose_name': 'Upcoming Exam', 'verbose_name_plural': 'Upcoming Exams'},
        ),
    ]
