# Generated by Django 4.2.8 on 2023-12-29 08:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_alter_exam_options_alter_upcomingexam_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingexam',
            name='image',
        ),
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='title',
            field=models.CharField(default=True, max_length=255, verbose_name='upcoming exam title'),
            preserve_default=False,
        ),
    ]
