# Generated by Django 4.2.8 on 2023-12-30 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_remove_upcomingexam_image_exam_image_exam_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='exam', verbose_name='image'),
        ),
    ]
