# Generated by Django 4.2.8 on 2023-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_alter_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingexam',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='meta keywords'),
        ),
    ]
