# Generated by Django 4.2.8 on 2023-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_upcomingexam_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingexam',
            old_name='keyword',
            new_name='meta_keyword',
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title'),
        ),
    ]
