# Generated by Django 4.2.8 on 2024-04-25 10:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0008_exam_meta_description_exam_meta_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True),
        ),
    ]
