# Generated by Django 4.2.8 on 2023-12-27 06:02

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Mobile number must be number!!!')], verbose_name='mobile number')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('favicon', models.ImageField(upload_to='siteconfig', verbose_name='favicon')),
                ('logo', models.ImageField(upload_to='siteconfig', verbose_name='logo')),
                ('primary_mobile', models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Mobile number must be number!!!')], verbose_name='primary mobile number')),
                ('secondary_mobile', models.CharField(blank=True, help_text='Alphabets and special characters are not allowed.', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Mobile number must be number!!!')], verbose_name='secondary mobile number')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp url')),
                ('playstore', models.URLField(blank=True, null=True, verbose_name='playstore url')),
                ('appstore', models.URLField(blank=True, null=True, verbose_name='appstore url')),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('image', models.ImageField(upload_to='core/slider', verbose_name='slider image')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
