# Generated by Django 4.2.8 on 2023-12-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook url'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram url'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin url'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter url'),
        ),
    ]
