# Generated by Django 4.2.8 on 2023-12-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_siteconfig_facebook_siteconfig_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube url'),
        ),
    ]
