# Generated by Django 4.2.8 on 2023-12-30 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_siteconfig_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='siteconfig', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='core/slider', verbose_name='slider image'),
        ),
    ]
