# Generated by Django 4.2.8 on 2024-01-10 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Mobile number must be number!!!')], verbose_name='mobile number'),
        ),
    ]
