# Generated by Django 4.2.8 on 2024-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='mobile number'),
        ),
    ]
