# Generated by Django 4.2.8 on 2024-01-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_about_meta_description_about_meta_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='meta_keyword',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='meta_title',
        ),
    ]
