# Generated by Django 4.2.8 on 2024-04-30 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_contact_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('note', models.TextField(verbose_name='note')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('phone', models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_mobile_format', message='Mobile number must be in the format "+911234567890".', regex='^\\+\\d{1,13}$')], verbose_name='mobile number')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='thread',
            field=models.URLField(blank=True, null=True, verbose_name='thread url'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_mobile',
            field=models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_mobile_format', message='Mobile number must be in the format "+911234567890".', regex='^\\+\\d{1,13}$')], verbose_name='primary mobile number'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='secondary_mobile',
            field=models.CharField(blank=True, help_text='Alphabets and special characters are not allowed.', max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile_format', message='Mobile number must be in the format "+911234567890".', regex='^\\+\\d{1,13}$')], verbose_name='secondary mobile number'),
        ),
    ]
