# Generated by Django 4.2.8 on 2023-12-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_alter_collegetype_options_and_more'),
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name', 'organization_type', 'college_type'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='collegegallery',
            options={'ordering': ['title'], 'verbose_name': 'College Gallery', 'verbose_name_plural': 'College Gallery'},
        ),
        migrations.AlterModelOptions(
            name='coursefee',
            options={'ordering': ['college', 'year_fees'], 'verbose_name': 'Course Fee', 'verbose_name_plural': 'Course Fees'},
        ),
        migrations.AlterModelOptions(
            name='eligibility',
            options={'ordering': ['-college'], 'verbose_name': 'Eligibility', 'verbose_name_plural': 'Eligibility'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-college'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='college',
            name='course_subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='General.coursesubcategory'),
        ),
    ]
