# Generated by Django 4.2.8 on 2023-12-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_alter_college_options_alter_collegegallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='application_end_date',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='application end date'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='application_start_date',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='application start date'),
        ),
    ]
