# Generated by Django 4.2.8 on 2023-12-29 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_alter_college_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='career',
        ),
        migrations.RemoveField(
            model_name='college',
            name='opportunity',
        ),
        migrations.AddField(
            model_name='college',
            name='career_opportunity',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Career & Opportunity'),
        ),
    ]
