# Generated by Django 4.2.8 on 2023-12-29 10:12

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0005_remove_college_career_remove_college_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='college/brochure'),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
