# Generated by Django 4.2.8 on 2023-12-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0006_alter_college_brochure_alter_college_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, verbose_name='College name'),
        ),
    ]
