# Generated by Django 4.2.8 on 2023-12-30 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0007_alter_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='college/image', verbose_name='college image'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='college/logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='collegegallery',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='college/gallery', verbose_name='image'),
        ),
    ]
