# Generated by Django 4.2.8 on 2023-12-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0008_alter_college_image_alter_college_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='keyword',
            new_name='meta_keyword',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='title',
            new_name='meta_title',
        ),
    ]
