# Generated by Django 4.2.8 on 2024-01-09 09:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0010_admissionblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200)),
                ('videofile', models.FileField(null=True, upload_to='college/videos', verbose_name='introductory video')),
                ('alt', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.college')),
            ],
            options={
                'verbose_name': 'Introductory Video',
                'verbose_name_plural': 'Introductory Videos',
            },
        ),
    ]
