# Generated by Django 4.2.8 on 2024-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0012_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='college',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook url'),
        ),
        migrations.AddField(
            model_name='college',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram url'),
        ),
        migrations.AddField(
            model_name='college',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin url'),
        ),
        migrations.AddField(
            model_name='college',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='telegram url'),
        ),
        migrations.AddField(
            model_name='college',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter url'),
        ),
        migrations.AddField(
            model_name='college',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='whatsapp url'),
        ),
        migrations.AddField(
            model_name='college',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube url'),
        ),
    ]
