# Generated by Django 4.2.8 on 2024-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0013_college_email_college_facebook_college_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website url'),
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
    ]
