# Generated by Django 4.2.8 on 2024-01-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0014_college_website_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegegallery',
            options={'ordering': ['title'], 'verbose_name': 'Award & Achivement', 'verbose_name_plural': 'Awards & Achivements'},
        ),
    ]
