# Generated by Django 4.2.8 on 2024-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0017_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='primary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='primary mobile number'),
        ),
        migrations.AddField(
            model_name='college',
            name='secondary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='secondary mobile number'),
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
