# Generated by Django 4.2.8 on 2024-01-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0018_college_primary_mobile_college_secondary_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
    ]
