# Generated by Django 4.2.8 on 2024-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_alter_admissionblog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='brochure',
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
