# Generated by Django 4.2.8 on 2024-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0021_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegevideo',
            name='videourl',
            field=models.URLField(blank=True, null=True, verbose_name='video url'),
        ),
        migrations.AlterField(
            model_name='collegevideo',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='college/videos', verbose_name='introductory video'),
        ),
    ]
