# Generated by Django 4.2.8 on 2024-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0026_college_placement_college_rating_college_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Affilation/Affilated College'),
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
