# Generated by Django 4.2.8 on 2024-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0027_college_affiliation_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
    ]
