# Generated by Django 4.2.8 on 2024-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0028_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
