# Generated by Django 4.2.8 on 2024-04-25 10:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0029_alter_admissionblog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
