# Generated by Django 4.2.8 on 2024-04-30 06:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0030_alter_admissionblog_slug_alter_admissionblog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True),
        ),
    ]
