# Generated by Django 4.2.8 on 2024-05-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0031_alter_admissionblog_slug_alter_college_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegevideo',
            name='videofile',
        ),
        migrations.AlterField(
            model_name='admissionblog',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
