# Generated by Django 4.2.8 on 2024-05-03 05:21

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alter_coursecategory_image'),
        ('Auth', '0009_user_is_college_alter_user_is_counsellor_and_more'),
        ('College', '0032_remove_collegevideo_videofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('title', models.CharField(max_length=255, verbose_name='upcoming exam title')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='post')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='College.college')),
                ('course_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.coursecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.collegeadmin')),
            ],
            options={
                'verbose_name': 'News & Article',
                'verbose_name_plural': 'News & Articles',
                'ordering': ['-title'],
            },
        ),
        migrations.DeleteModel(
            name='AdmissionBlog',
        ),
    ]
