# Generated by Django 4.2.8 on 2024-05-03 05:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0034_news_image_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.college'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post',
            field=ckeditor.fields.RichTextField(verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
