# Generated by Django 4.2.8 on 2024-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0036_collegenews_college_views_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegenews',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
