# Generated by Django 4.2.8 on 2024-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0038_alter_collegenews_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegenews',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAFT')], max_length=10),
        ),
    ]
