# Generated by Django 4.2.8 on 2024-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0039_alter_collegenews_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegenews',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
    ]
