# Generated by Django 4.2.8 on 2024-06-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alter_coursecategory_image'),
        ('College', '0042_alter_collegenews_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefee',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.coursecategory'),
        ),
    ]
