# Generated by Django 4.2.8 on 2023-12-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['name'], 'verbose_name': 'Religion', 'verbose_name_plural': 'Religions'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name', 'country'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
    ]
