# Generated by Django 4.2.8 on 2023-12-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegetype',
            options={'ordering': ['name'], 'verbose_name': 'College Type', 'verbose_name_plural': 'College Types'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['name'], 'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursestream',
            options={'ordering': ['name', 'course_subcategory'], 'verbose_name': 'Course Stream', 'verbose_name_plural': 'Course Streams'},
        ),
        migrations.AlterModelOptions(
            name='coursesubcategory',
            options={'ordering': ['course_name'], 'verbose_name': 'Course Subcategory', 'verbose_name_plural': 'Course Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['name'], 'verbose_name': 'Course Type', 'verbose_name_plural': 'Course Types'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'ordering': ['name'], 'verbose_name': 'Organization Type', 'verbose_name_plural': 'Organization Types'},
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='course subcategory duration (In Year)'),
        ),
    ]
