# Generated by Django 4.2.8 on 2023-12-30 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_alter_collegetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='course_category/', verbose_name='course category image'),
        ),
    ]
