# Generated by Django 4.2.8 on 2023-12-30 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile', verbose_name='profile picture'),
        ),
    ]
