# Generated by Django 4.2.8 on 2024-01-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_counselloradmin_user_is_counsellor_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='student status'),
        ),
    ]
