# Generated by Django 4.2.8 on 2024-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_education_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_college',
            field=models.BooleanField(default=False, verbose_name='college status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_counsellor',
            field=models.BooleanField(default=False, verbose_name='counsellor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the staff can log into this admin site.', verbose_name='staff status'),
        ),
    ]
