# Generated by Django 4.2.8 on 2024-05-27 05:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_user_is_college_alter_user_is_counsellor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselloradmin',
            options={'verbose_name': 'Company User', 'verbose_name_plural': 'Company Users'},
        ),
        migrations.RenameField(
            model_name='counselloradmin',
            old_name='pancard',
            new_name='pan_no',
        ),
        migrations.AddField(
            model_name='counselloradmin',
            name='pan_card',
            field=imagekit.models.fields.ProcessedImageField(default=True, upload_to='counsellor/pan', verbose_name='pan card'),
            preserve_default=False,
        ),
    ]
