# Generated by Django 4.2.8 on 2024-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_counselloradmin_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselloradmin',
            name='company_certificate',
        ),
        migrations.RemoveField(
            model_name='counselloradmin',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='counselloradmin',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='counselloradmin',
            name='pan_no',
        ),
    ]
