# Generated by Django 4.2.8 on 2024-01-16 09:28

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0002_alter_category_options_alter_country_options_and_more'),
        ('Auth', '0004_counselloradmin_user_is_counsellor_alter_user_dob'),
        ('General', '0003_alter_coursecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('city', models.CharField(max_length=70, verbose_name='city')),
                ('current_address', models.TextField(blank=True, verbose_name='current address')),
                ('permanent_address', models.TextField(blank=True, verbose_name='permanent address')),
                ('zipcode', models.IntegerField(null=True, verbose_name='zipcode')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website url')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp url')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram url')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter url')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtube url')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram url')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='counsellor/logo', verbose_name='logo')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='counsellor/image', verbose_name='image')),
                ('success_story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, max_length=8, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='company_name', unique=True)),
                ('area_of_operation', models.ManyToManyField(to='General.coursecategory')),
                ('counsellor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.counselloradmin')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.state')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=20, verbose_name='organization title')),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Types',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website url')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp url')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram url')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter url')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtube url')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram url')),
                ('name', models.CharField(max_length=100, verbose_name='director name')),
                ('profile', imagekit.models.fields.ProcessedImageField(upload_to='counsellor/profile', verbose_name='profile')),
                ('id_proof', models.FileField(upload_to='counsellor/id_proof')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.counsellor')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.organizationtype', verbose_name='organization type')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='CounsellorTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='Feedback')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.counselloradmin')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
