# Generated by Django 4.2.8 on 2024-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='primary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='primary mobile number'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='secondary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='secondary mobile number'),
        ),
        migrations.AddField(
            model_name='director',
            name='primary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='primary mobile number'),
        ),
        migrations.AddField(
            model_name='director',
            name='secondary_mobile',
            field=models.CharField(blank=True, help_text="mobile number must be entered in the format: '+911234567890'.", max_length=15, null=True, verbose_name='secondary mobile number'),
        ),
    ]
