# Generated by Django 4.2.8 on 2024-01-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alter_coursecategory_image'),
        ('Auth', '0004_counselloradmin_user_is_counsellor_alter_user_dob'),
        ('Counsellor', '0002_counsellor_primary_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.counsellor')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.coursecategory')),
                ('course_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.coursestream')),
                ('course_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.coursesubcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.student')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
