# Generated by Django 4.2.8 on 2024-02-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0003_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellortestimonial',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.counsellor'),
        ),
    ]
