# Generated by Django 4.2.8 on 2024-02-24 07:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0004_alter_counsellortestimonial_counsellor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('question', models.CharField(max_length=200, verbose_name='questions')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='answer')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='Counsellor.counsellor')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-counsellor'],
            },
        ),
    ]
