# Generated by Django 4.2.8 on 2024-04-25 10:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='company_name', unique=True),
        ),
    ]
