# Generated by Django 4.2.8 on 2024-04-30 06:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0006_alter_counsellor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='company_name', unique=True),
        ),
    ]
