# Generated by Django 4.2.8 on 2024-05-18 07:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0009_counsellor_views_alter_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='overview',
            field=ckeditor.fields.RichTextField(default=True, verbose_name='overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellortestimonial',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='counsellor/testimonial', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='leads',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], max_length=10),
        ),
        migrations.CreateModel(
            name='CounsellorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200)),
                ('videourl', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('alt', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.counsellor')),
            ],
            options={
                'verbose_name': 'Introductory Video',
                'verbose_name_plural': 'Introductory Videos',
            },
        ),
        migrations.CreateModel(
            name='CounsellorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=200)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='counsellor/gallery', verbose_name='image')),
                ('alt', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.counsellor')),
            ],
            options={
                'verbose_name': 'Award & Achivement',
                'verbose_name_plural': 'Awards & Achivements',
                'ordering': ['title'],
            },
        ),
    ]
