# Generated by Django 4.2.8 on 2024-05-27 06:40

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0013_director_identity_alter_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='company_certificate',
            field=models.FileField(default=True, upload_to='counsellor/company', verbose_name='company certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellor',
            name='gst',
            field=models.CharField(blank=True, help_text='Special characters are not allowed', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]*$', message='GST Number must be Alphanumeric!!!'), django.core.validators.MaxLengthValidator(15, 'GST Number must be 15 digits!!!'), django.core.validators.MinLengthValidator(15, 'GST Number must be have at least 15 digits!!!')], verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='pan_card',
            field=imagekit.models.fields.ProcessedImageField(default=True, upload_to='counsellor/pan', verbose_name='pan card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellor',
            name='pan_no',
            field=models.CharField(blank=True, help_text='Special characters are not allowed', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]*$', message='Pan Card Number must be Alphanumeric!!!'), django.core.validators.MaxLengthValidator(10, 'Pan Card Number must be 10 digits!!!'), django.core.validators.MinLengthValidator(10, 'Pan Card Number must be have at least 10 digits!!!')], verbose_name='Pan Card Number'),
        ),
    ]
